[webservers]

web-1 ansible_host= fqdn=fhmct8popf4smo125ilr.auto.internal

web-2 ansible_host= fqdn=fhm8p7t2k1alli7hb67h.auto.internal


[databases]

main ansible_host= fqdn=fhmf9v6asd8lrjh29q5h.auto.internal

replica ansible_host= fqdn=fhm4tv6sec0teuiksirs.auto.internal


[storage]
%
storage ansible_host= fqdn=fhmkt1158ans19tasr6q.auto.internal
%
