[webservers]

web-1 ansible_host=158.160.36.89 fqdn=fhmhgon4mi79r5nb19iq.auto.internal

web-2 ansible_host=158.160.46.202 fqdn=fhm5rhidd6dco75qflsb.auto.internal


[databases]

main ansible_host=158.160.33.19 fqdn=fhm13t1rpj42flg582p6.auto.internal

replica ansible_host=51.250.90.95 fqdn=fhmuvdrbm7k2b3p1nd3h.auto.internal


[storage]

storage ansible_host=51.250.69.198 fqdn=fhm5tun4fqin2qrsmo5o.auto.internal

