[webservers]

web-1 ansible_host=89.169.135.119 fqdn=fhmea41frjj2fp6fso6b.auto.internal

web-2 ansible_host=89.169.130.12 fqdn=fhm5l9c86ed85hkg3ko5.auto.internal


[databases]

main ansible_host=89.169.154.0 fqdn=fhmuja34ci7173oa5029.auto.internal

replica ansible_host=84.201.131.172 fqdn=fhmk25iiorqtro7m31u1.auto.internal


[storage]

storage ansible_host=62.84.124.176 fqdn=fhm5kv82hgu34adj3c53.auto.internal

